name: Update RSS

on:
  schedule:
    - cron: "0 */6 * * *"   # 每6小时更新一次
  workflow_dispatch:         # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch feeds
        run: |
          python fetch.py

      - name: Commit & Push if changed
        run: |
          git config user.name "rss-bot"
          git config user.email "bot@example.com"
          git add feeds/*.xml index.html || true
          git commit -m "chore: update feeds $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
